export const BUILDER_ENGINE_SCRIPT = `
<script id="jarvis-builder-engine">
(function() {
  window.addEventListener('DOMContentLoaded', () => {
    initBuilder();
  });

  // Also re-init if DOM changes (e.g., inline edit mode or drops)
  let domTimer;
  const observer = new MutationObserver(() => {
    clearTimeout(domTimer);
    domTimer = setTimeout(initBuilder, 500);
  });
  observer.observe(document.body, { childList: true, subtree: true });

  let draggedEl = null;
  let isInternalDrag = false;

  function initBuilder() {
    const sections = document.querySelectorAll('section, header, footer');
    
    sections.forEach(sec => {
      // Avoid attaching multiple times
      if (sec.getAttribute('data-jarvis-dnd')) return;
      sec.setAttribute('data-jarvis-dnd', 'true');
      sec.setAttribute('draggable', 'true');
      
      // Apply subtle grab cursor
      sec.style.cursor = 'grab';
      
      sec.addEventListener('dragstart', (e) => {
        if (sec.getAttribute('contenteditable') === 'true') {
          e.preventDefault();
          return;
        }
        draggedEl = sec;
        isInternalDrag = true;
        e.dataTransfer.effectAllowed = 'move';
        sec.style.opacity = '0.4';
      });

      sec.addEventListener('dragend', () => {
        sec.style.opacity = '1';
        sec.style.borderTop = '';
        sec.style.borderBottom = '';
        draggedEl = null;
        isInternalDrag = false;
        syncHtml();
      });

      sec.addEventListener('dragover', (e) => {
        e.preventDefault(); // allow drop
        e.dataTransfer.dropEffect = 'move';
        
        const bounding = sec.getBoundingClientRect();
        const offset = bounding.y + (bounding.height / 2);
        
        // Remove previous borders
        document.querySelectorAll('[data-jarvis-dnd]').forEach(el => {
          el.style.borderTop = '';
          el.style.borderBottom = '';
        });

        if (e.clientY - offset > 0) {
          sec.style.borderBottom = '4px solid #6366f1'; // indigo-500
        } else {
          sec.style.borderTop = '4px solid #6366f1';
        }
      });

      sec.addEventListener('dragleave', () => {
        sec.style.borderTop = '';
        sec.style.borderBottom = '';
      });

      sec.addEventListener('drop', (e) => {
        e.preventDefault();
        sec.style.borderTop = '';
        sec.style.borderBottom = '';
        
        const bounding = sec.getBoundingClientRect();
        const offset = bounding.y + (bounding.height / 2);
        const insertAfter = e.clientY - offset > 0;

        // Internal reordering
        if (isInternalDrag && draggedEl && draggedEl !== sec) {
          if (insertAfter) {
            sec.insertAdjacentElement('afterend', draggedEl);
          } else {
            sec.insertAdjacentElement('beforebegin', draggedEl);
          }
          // sync happens in dragend
        } 
        // Drop from parent sidebar
        else if (!isInternalDrag) {
          const componentType = e.dataTransfer.getData('javis-component');
          if (componentType) {
            const id = 'placeholder-' + Date.now();
            const placeholder = document.createElement('section');
            placeholder.id = id;
            placeholder.innerHTML = '<div style="padding:60px 20px;text-align:center;background:var(--surface);border:2px dashed var(--border);border-radius:var(--radius);margin:20px;font-family:sans-serif;color:var(--text);font-weight:500;">✨ Generating ' + componentType + ' component...</div>';
            
            if (insertAfter) {
              sec.insertAdjacentElement('afterend', placeholder);
            } else {
              sec.insertAdjacentElement('beforebegin', placeholder);
            }
            
            window.parent.postMessage({ type: 'jarvis:generate-component', componentType, placeholderId: id }, '*');
          }
        }
      });
    });
  }

  // Listen for component generated by parent
  window.addEventListener('message', (e) => {
    if (e.data.type === 'jarvis:replace-placeholder') {
      const placeholder = document.getElementById(e.data.placeholderId);
      if (placeholder) {
        // Create a temporary container to parse the new HTML
        const temp = document.createElement('div');
        temp.innerHTML = e.data.html.trim();
        const newSection = temp.firstElementChild;
        if (newSection) {
          placeholder.replaceWith(newSection);
          initBuilder(); // re-init to make the new section draggable
          syncHtml();
        } else {
          placeholder.remove();
        }
      }
    }
  });

  function syncHtml() {
    // Clone body to strip out injected attributes/scripts before saving
    const clone = document.documentElement.cloneNode(true);
    
    const engine = clone.querySelector('#jarvis-builder-engine');
    if (engine) engine.remove();
    
    clone.querySelectorAll('[data-jarvis-dnd]').forEach(el => {
      el.removeAttribute('data-jarvis-dnd');
      el.removeAttribute('draggable');
      el.style.cursor = '';
      el.style.opacity = '';
      el.style.borderTop = '';
      el.style.borderBottom = '';
      if (el.getAttribute('style') === '') el.removeAttribute('style');
    });

    const cleanHtml = "<!doctype html>\\n" + clone.outerHTML;
    window.parent.postMessage({ type: 'jarvis:save', html: cleanHtml }, '*');
  }
})();
</script>
`;
