import { NextResponse } from "next/server";
import { requireUser } from "@/lib/supabase/server";
import { queryOne } from "@/lib/dsql";
import PptxGenJS from "pptxgenjs";

export async function POST(req: Request) {
  let user;
  try { ({ user } = await requireUser()); }
  catch { return NextResponse.json({ error: "unauthorized" }, { status: 401 }); }

  const { id } = await req.json();
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });

  const strategy = await queryOne(
    "SELECT * FROM strategies WHERE id = $1 AND user_id = $2",
    [id, user.id]
  ).catch(() => null);

  if (!strategy) return NextResponse.json({ error: "not found" }, { status: 404 });

  const prs = new PptxGenJS();
  prs.layout = "LAYOUT_WIDE";

  // Title slide
  const titleSlide = prs.addSlide();
  titleSlide.background = { color: "0f172a" };
  titleSlide.addText(strategy.title, {
    x: 0.5, y: 1.8, w: "90%", h: 1.2,
    fontSize: 36, bold: true, color: "f8fafc",
    fontFace: "Calibri",
  });
  titleSlide.addText(`Generated by Javis AI · ${new Date(strategy.created_at).toLocaleDateString()}`, {
    x: 0.5, y: 3.2, w: "90%", h: 0.5,
    fontSize: 14, color: "94a3b8",
    fontFace: "Calibri",
  });

  // Content slides — split by sections (## headings)
  const lines = (strategy.content as string).split("\n");
  let currentSection = "";
  let currentBody: string[] = [];

  const flush = () => {
    if (!currentSection && currentBody.length === 0) return;
    const slide = prs.addSlide();
    slide.background = { color: "ffffff" };
    if (currentSection) {
      slide.addText(currentSection, {
        x: 0.5, y: 0.4, w: "90%", h: 0.8,
        fontSize: 22, bold: true, color: "0f172a",
        fontFace: "Calibri",
      });
    }
    const body = currentBody.join("\n").trim();
    if (body) {
      slide.addText(body, {
        x: 0.5, y: 1.3, w: "90%", h: 4,
        fontSize: 13, color: "334155",
        fontFace: "Calibri",
        valign: "top",
        wrap: true,
      });
    }
    currentSection = "";
    currentBody = [];
  };

  for (const line of lines) {
    if (line.startsWith("## ")) {
      flush();
      currentSection = line.replace(/^## /, "");
    } else if (line.startsWith("# ")) {
      // skip top-level title (already on title slide)
    } else {
      currentBody.push(line);
    }
  }
  flush();

  const buffer = (await prs.write({ outputType: "arraybuffer" })) as ArrayBuffer;
  const bytes = new Uint8Array(buffer);

  return new NextResponse(bytes, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "Content-Disposition": `attachment; filename="${encodeURIComponent(strategy.title)}.pptx"`,
    },
  });
}
